import torch
from typing import Tuple
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

class EduGuardResponseAuditor:
    """
    EGS Stage 3: Holistic Response Auditor
    
    This module is designed to audit the *output* generated by an Educational LLM.
    It acts as a final filter to intercept harmful content before it reaches the student.
    """

    def __init__(self, model_path_post: str):
        """
        Initialize the response moderation model.

        Args:
            model_path_post (str): Path to your Response Auditor model (e.g., DeBERTa-v3-Base finetuned).
        """
        self.device = 0 if torch.cuda.is_available() else -1
        
        print(f"Loading Holistic Response Auditor from {model_path_post}...")
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(model_path_post)
            self.model = AutoModelForSequenceClassification.from_pretrained(model_path_post)
            
            # Initialize pipeline for easier inference
            self.classifier = pipeline(
                "text-classification", 
                model=self.model, 
                tokenizer=self.tokenizer, 
                device=self.device
            )
            print("Response Auditor loaded successfully.")
        except Exception as e:
            print(f"Error loading model: {e}")
            raise e

    def audit_response(self, llm_output_text: str, threshold: float = 0.5, stride: int = 256) -> Tuple[bool, float]:
        """
        Audits the LLM-generated response using a sliding window approach.
        
        Args:
            llm_output_text (str): [CRITICAL] The full text generated by the LLM (not the user query).
            threshold (float): Probability threshold for unsafe content (Default: 0.5).
            stride (int): Step size for the sliding window (Default: 256). 
                          This implies a 50% overlap to prevent context loss at boundaries.
        
        Returns:
            tuple: (is_safe (bool), max_unsafe_score (float))
            - is_safe: True if the response passes the audit, False if it should be blocked.
            - max_unsafe_score: The highest risk score detected across all windows.
        """
        # Return safe immediately if text is empty
        if not llm_output_text or not llm_output_text.strip():
            return True, 0.0

        # 1. Preprocessing: Tokenize the entire text to manage windowing manually.
        # We set add_special_tokens=False because the pipeline adds [CLS]/[SEP] for each chunk later.
        encoding = self.tokenizer(llm_output_text, add_special_tokens=False, return_tensors="pt")
        input_ids = encoding["input_ids"][0]
        total_len = len(input_ids)

        # Maximum sequence length for BERT-like models is usually 512.
        # We reserve 2 tokens for the special tokens added by the pipeline.
        chunk_size = 510 
        
        start = 0
        max_unsafe_score = 0.0

        # Case A: Short text fits in a single chunk
        if total_len <= chunk_size:
            return self._check_chunk(llm_output_text, threshold)

        # Case B: Long text requires sliding window detection
        while start < total_len:
            # Define window end
            end = min(start + chunk_size, total_len)
            
            # Slice tokens and decode back to text
            chunk_ids = input_ids[start:end]
            chunk_text = self.tokenizer.decode(chunk_ids, skip_special_tokens=True)
            
            # Skip empty chunks
            if not chunk_text.strip():
                if end == total_len: break
                start += stride
                continue

            # Audit the current chunk
            is_safe, score = self._check_chunk(chunk_text, threshold)
            max_unsafe_score = max(max_unsafe_score, score)

            # Fail-Fast Mechanism: If ANY chunk is unsafe, block the entire response immediately.
            if not is_safe:
                return False, max_unsafe_score

            # Break if we have processed the entire sequence
            if end == total_len:
                break
            
            # Move the window forward
            start += stride

        # If loop completes, the entire text is safe
        return True, max_unsafe_score

    def _check_chunk(self, text_chunk: str, threshold: float) -> Tuple[bool, float]:
        """Internal helper: Run inference on a single text string."""
        # truncation=True is a safety net here
        output = self.classifier(text_chunk, truncation=True, max_length=512)
        item = output[0]

        # Calculate Unsafe Probability 
        # Assumption: LABEL_1 = Safe, LABEL_0 = Unsafe.
        # Please adjust this logic if your model labels are swapped.
        if item["label"] == "LABEL_1":
            unsafe_score = 1 - item["score"]
        else:
            unsafe_score = item["score"]

        is_safe = unsafe_score < threshold
        return is_safe, unsafe_score

# --- Usage Example ---
if __name__ == "__main__":
    # Configuration: Replace with your actual model path
    model_path = "/your model path" 

    # Initialize the Auditor
    auditor = EduGuardResponseAuditor(model_path_post=model_path)
    
    # Simulate obtaining the output stream/string from your LLM generation function
    llm_draft_response = "The LLM generated content goes here..." 
    
    # Execute Audit
    print(f"Auditing response (Length: {len(llm_draft_response)} chars)...")
    is_safe, risk_score = auditor.audit_response(llm_draft_response)

    if is_safe:
        print(f"Audit Passed: Content is safe to display. (Max Risk Score: {risk_score:.4f})")
    else:
        print(f"Audit Blocked: Content contains risk. (Max Risk Score: {risk_score:.4f})")